routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('employees','EmployeeController');
    Route::resource('events','EventController');
    Route::resource('companies','CompanyController');
    Route::post('companies/getEmployees', 'CompanyController@getEmployees')->name('companies.getEmployees');
});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    @include('navigation')

    @include('event.create')

    @include('event.index')
@endsection

resources/views/navigation.blade.php
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            @if (session('status'))
                <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                </div>
            @endif
            @if(count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="list-group">
                <a href="{{ route('home') }}"
                   class="list-group-item {{ (request()->is('home*')) ? 'active' : 'list-group-item-action' }}">Главная</a>
                <a href="{{ route('employees.index') }}"
                   class="list-group-item {{ (request()->is('employees*')) ? 'active' : 'list-group-item-action' }}">Сотрудники</a>
                <a href="{{ route('companies.index') }}"
                   class="list-group-item {{ (request()->is('companies*')) ? 'active' : 'list-group-item-action' }}">Компании</a>
            </div>
        </div>
    </div>
</div>