routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('employees','EmployeeController');
    Route::resource('events','EventController');
    Route::resource('companies','CompanyController');
    Route::post('companies/getEmployees', 'CompanyController@getEmployees')->name('companies.getEmployees');
});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $fillable = ['surname', 'name', 'patronymic', 'company_id', 'email'];

    public function company()
    {
        return $this->belongsTo('App\Models\Company');
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\EmployeeRequest;
use App\Models\Company;
use App\Models\Employee;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (!view()->exists('employee.index')) {
            abort(404);
        }
        $employees = Employee::with('company')->get();
        return view('employee.index', compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (!view()->exists('employee.create')) {
            abort(404);
        }
        $companies = Company::all();
        return view('employee.create', compact('companies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\EmployeeRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeRequest $request)
    {
        Employee::create($request->all());
        return redirect()->route('employees.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Employee $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Employee $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        if (!view()->exists('employee.edit')) {
            abort(404);
        }
        $companies = Company::all();
        return view('employee.edit', compact('companies', 'employee'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\EmployeeRequest $request
     * @param  \App\Models\Employee $employee
     * @return \Illuminate\Http\Response
     */
    public function update(EmployeeRequest $request, Employee $employee)
    {
        $employee->update($request->all());
        return redirect()->route('employees.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Employee $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();
        return redirect()->route('employees.index');
    }
}

resources/views/employee/create.blade.php
@extends('layouts.app')

@section('content')
    @include('navigation')
    <div class="container p-2">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form action="{{ route('employees.store') }}" method="POST">
                    @csrf
                    <fieldset class="border p-2">
                        <legend class="w-auto btn-sm text-primary">Форма добавления сотрудника</legend>
                        <div class="form-group">
                            <label for="surname">Фамилия</label>
                            <input type="text" class="form-control" id="surname" name="surname" value="{{ @old('surname') }}" placeholder="Фамилия">
                        </div>

                        <div class="form-group">
                            <label for="name">Имя</label>
                            <input type="text" class="form-control" id="name" name="name" value="{{ @old('name') }}" placeholder="Имя">
                        </div>

                        <div class="form-group">
                            <label for="patronymic">Отчество</label>
                            <input type="text" class="form-control" id="patronymic" name="patronymic"
                                   value="{{ @old('patronymic') }}" placeholder="Отчество">
                        </div>

                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="email" name="email"
                                   value="{{ @old('email') }}" placeholder="Email">
                        </div>

                        <div class="form-group">
                            <label for="company_id">Компания</label>
                            <select id="company_id" class="form-control" name="company_id">
                                @foreach($companies as $company)
                                    <option value="{{ $company->id }}">{{ $company->name }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group p-2">
                            <button type="submit" class="btn btn-outline-success">Сохранить</button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/employee/edit.blade.php
@extends('layouts.app')

@section('content')
    @include('navigation')
    <div class="container p-2">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form action="{{ route('employees.update', $employee) }}" method="POST">
                    {{ method_field('PATCH') }}
                    @csrf
                    <fieldset class="border p-2">
                        <legend class="w-auto btn-sm text-primary">Форма редактирования сотрудника</legend>
                        <div class="form-group">
                            <label for="surname">Фамилия</label>
                            <input type="text" class="form-control" id="surname" name="surname"
                                   value="{{ $employee->surname }}" placeholder="Фамилия">
                        </div>

                        <div class="form-group">
                            <label for="name">Имя</label>
                            <input type="text" class="form-control" id="name" name="name" value="{{ $employee->name }}"
                                   placeholder="Имя">
                        </div>

                        <div class="form-group">
                            <label for="patronymic">Отчество</label>
                            <input type="text" class="form-control" id="patronymic" name="patronymic"
                                   value="{{ $employee->patronymic }}" placeholder="Отчество">
                        </div>

                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="email" name="email"
                                   value="{{ $employee->email }}" placeholder="Email">
                        </div>

                        <div class="form-group">
                            <label for="company_id">Компания</label>
                            <select id="company_id" class="form-control" name="company_id">
                                @foreach($companies as $company)
                                    <option {{ ($employee->company_id == $company->id) ? 'selected' : '' }}
                                        value="{{ $company->id }}">{{ $company->name }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group p-2">
                            <button type="submit" class="btn btn-outline-success">Обновить</button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/employee/index.blade.php
@extends('layouts.app')

@section('content')
    @include('navigation')

    <div class="container p-2">
        <div class="row p-2">
            <a href="{{ route('employees.create') }}" class="btn btn-success">Добавить сотрудника</a>
        </div>
        <div class="row justify-content-center">
            <table class="table">
                <thead class="thead-light">
                <tr>
                    <th>#</th>
                    <th>Фамилия</th>
                    <th>Имя</th>
                    <th>Отчество</th>
                    <th>Компания</th>
                    <th>Email</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($employees as $k => $employee)
                    <tr>
                        <td>{{ $k + 1 }}</td>
                        <td>{{ $employee->surname }}</td>
                        <td>{{ $employee->name }}</td>
                        <td>{{ $employee->patronymic }}</td>
                        <td>{{ $employee->company->name }}</td>
                        <td>{{ $employee->email }}</td>
                        <td>
                            <a href="{{ route('employees.edit', $employee) }}"
                               class="btn btn-block btn-primary btn-sm">edit</a>
                            <form method="post" action="{{ route('employees.destroy', $employee) }}"
                                  accept-charset="UTF-8" class="btn-block">
                                @csrf
                                <input type="hidden" name="_method" value="delete"/>
                                <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
                                <input class="btn btn-danger btn-block btn-sm" type="submit" value="delete"/>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection