routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('employees','EmployeeController');
    Route::resource('events','EventController');
    Route::resource('companies','CompanyController');
    Route::post('companies/getEmployees', 'CompanyController@getEmployees')->name('companies.getEmployees');
});

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $fillable = ['name'];

    protected $table = 'companies';

    public function employees()
    {
        return $this->hasMany('App\Models\Employee');
    }

    public function responsible_employees()
    {
        return $this->hasMany('App\Models\Employee')->where('responsible', 1);
    }

    public function events()
    {
        return $this->hasMany(Event::class)
            ->orderBy('date', 'asc')
            ->orderBy('shift', 'asc');
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CompanyRequest;
use App\Models\Company;
use Illuminate\Http\Request;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (!view()->exists('company.index')) {
            abort(404);
        }
        $companies = Company::all();
        return view('company.index', compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (!view()->exists('company.create')) {
            abort(404);
        }
        return view('company.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\CompanyRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompanyRequest $request)
    {
        Company::create($request->all());
        return redirect()->route('companies.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Company $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Company $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        if (!view()->exists('company.edit')) {
            abort(404);
        }
        return view('company.edit', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\CompanyRequest $request
     * @param  \App\Models\Company $company
     * @return \Illuminate\Http\Response
     */
    public function update(CompanyRequest $request, Company $company)
    {
        $company->update($request->all());
        return redirect()->route('companies.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Company $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        $company->delete();
        return redirect()->route('companies.index');
    }

    public function getEmployees(Request $request)
    {
        if ($request->ajax() && isset($request->company_id)) {
            $employees = Company::find($request->company_id)->employees()->get();
            return $employees;
        }
    }
}

resources/views/company/create.blade.php
@extends('layouts.app')

@section('content')
    @include('navigation')
    <div class="container p-2">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form action="{{ route('companies.store') }}" method="POST">
                    @csrf
                    <fieldset class="border p-2">
                        <legend class="w-auto btn-sm text-primary">Форма добавления компании</legend>
                        <div class="form-group">
                            <label for="name">Название</label>
                            <input type="text" class="form-control" id="name" name="name" value="{{ @old('name') }}"
                                   placeholder="Название">
                        </div>
                        <div class="form-group p-2">
                            <button type="submit" class="btn btn-outline-success">Сохранить</button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/company/edit.blade.php
@extends('layouts.app')

@section('content')
    @include('navigation')
    <div class="container p-2">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form action="{{ route('companies.update', $company) }}" method="POST">
                    {{ method_field('PATCH') }}
                    @csrf
                    <fieldset class="border p-2">
                        <legend class="w-auto btn-sm text-primary">Форма редактирования компании</legend>
                        <div class="form-group">
                            <label for="name">Название</label>
                            <input type="text" class="form-control" id="name" name="name" value="{{ $company->name }}"
                                   placeholder="Название">
                        </div>
                        <div class="form-group p-2">
                            <button type="submit" class="btn btn-outline-success">Обновить</button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/company/index.blade.php
@extends('layouts.app')

@section('content')
    @include('navigation')

    <div class="container p-2">
        <div class="row p-2">
            <a href="{{ route('companies.create') }}" class="btn btn-success">Добавить компанию</a>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-5">
                <table class="table">
                    <thead class="thead-light">
                    <tr>
                        <th>#</th>
                        <th>Название</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($companies as $k => $company)
                        <tr>
                            <td>{{ $k + 1 }}</td>
                            <td>{{ $company->name }}</td>
                            <td>
                                <a href="{{ route('companies.edit', $company) }}"
                                   class="btn btn-block btn-primary btn-sm">edit</a>
                                <form method="post" action="{{ route('companies.destroy', $company) }}"
                                      accept-charset="UTF-8" class="btn-block">
                                    @csrf
                                    <input type="hidden" name="_method" value="delete"/>
                                    <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
                                    <input class="btn btn-danger btn-block btn-sm" type="submit" value="delete"/>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection