routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('employees','EmployeeController');
    Route::resource('events','EventController');
    Route::resource('companies','CompanyController');
    Route::post('companies/getEmployees', 'CompanyController@getEmployees')->name('companies.getEmployees');
});

app/Models/Event.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    protected $fillable = ['project_name', 'price', 'type_work', 'company_id', 'employee_id', 'date', 'shift'];

    protected $dates = ['date'];

    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    public function employee()
    {
        return $this->belongsTo(Employee::class);
    }
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Models\Company;
use App\Models\Event;
use Illuminate\Http\Request;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $event = Event::create($request->all());
        return $event;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Event $event
     * @return \Illuminate\Http\Response
     */
    public function show(Event $event)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Event $event
     * @return \Illuminate\Http\Response
     */
    public function edit(Event $event)
    {
        $companies = Company::all();
        $employee = $event->employee()->first();
        if (!view()->exists('event.edit')) {
            abort(404);
        }
        return view('event.edit', compact('event', 'companies', 'employee'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Event $event
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Event $event)
    {
        $event->update($request->all());
        return redirect()->route('home');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Event $event
     * @return \Illuminate\Http\Response
     */
    public function destroy(Event $event)
    {
        $event->delete();
        return redirect()->route('home');
    }
}

resources/views/event/create.blade.php
<div class="container p-2">
    <div class="row">
        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#eventModel">
            Добавить событие
        </button>

        <div class="modal fade" id="eventModel" tabindex="-1" role="dialog" aria-labelledby="eventModel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModal3Label">Новое событие</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form id="eventForm">
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="project_name">Название проекта</label>
                                <input type="text" class="form-control" id="project_name" name="project_name"
                                       placeholder="Название проекта" required>
                            </div>

                            <div class="form-group">
                                <label for="name">Стоимость работ</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">$</span>
                                    </div>
                                    <input type="number" value="1000" min="0" step="0.01" data-number-to-fixed="2"
                                           data-number-stepfactor="100" class="form-control currency" id="price"
                                           name="price"/>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="type_work">Тип работ</label>
                                <input type="text" class="form-control" id="type_work" name="type_work"
                                       placeholder="Название проекта" required>
                            </div>

                            <div class="form-group">
                                <label for="company_id">Компания</label>
                                <select id="company_id" class="form-control" name="company_id" required>
                                    <option value="" selected disabled hidden>Choose here</option>
                                    @foreach($companies as $company)
                                        <option value="{{ $company->id }}">{{ $company->name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group employee_input">
                                <label for="employee_id">Ответственный сотрудник</label>
                                <select id="employee_id" class="form-control" name="employee_id" required>
                                    <option value="" selected disabled hidden>Choose here</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="date">Дата</label>
                                <input type="date" class="form-control" id="date" name="date"
                                       placeholder="Дата" required>
                            </div>

                            <div class="form-group">
                                <label for="shift">Смена</label>
                                <select id="shift" class="form-control" name="shift" required>
                                    <option value="" selected disabled hidden>Choose here</option>
                                    <option value="1">Первая смена</option>
                                    <option value="2">Вторая смена</option>
                                    <option value="3">Третья смена</option>
                                </select>
                            </div>
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>

resources/views/event/edit.blade.php
@extends('layouts.app')

@section('content')
    @include('navigation')
    <div class="container p-2">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form action="{{ route('events.update', $event) }}" method="POST">
                    {{ method_field('PATCH') }}
                    @csrf
                    <fieldset class="border p-2">
                        <legend class="w-auto btn-sm text-primary">Форма редактирования события</legend>
                        <div class="form-group">
                            <label for="project_name">Название проекта</label>
                            <input type="text" class="form-control" id="project_name" name="project_name"
                                   value="{{ $event->project_name }}" required>
                        </div>

                        <div class="form-group">
                            <label for="name">Стоимость работ</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">$</span>
                                </div>
                                <input type="number" value="{{ $event->price }}" min="0" step="0.01"
                                       data-number-to-fixed="2"
                                       data-number-stepfactor="100" class="form-control currency" id="price"
                                       name="price"/>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="type_work">Тип работ</label>
                            <input type="text" value="{{ $event->type_work }}" class="form-control" id="type_work"
                                   name="type_work" placeholder="Название проекта" required>
                        </div>

                        <div class="form-group">
                            <label for="company_id">Компания</label>
                            <select id="company_id" class="form-control" name="company_id" required>
                                <option value="" selected disabled hidden>Choose here</option>
                                @foreach($companies as $company)
                                    <option value="{{ $company->id }}" {{ ($company->id === $event->company_id) ? 'selected' : ''}}>{{ $company->name }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group employee_input">
                            <label for="employee_id">Ответственный сотрудник</label>
                            <select id="employee_id" class="form-control" name="employee_id" required>
                                <option value="{{ $employee->id }}"
                                        selected>{{ $employee->surname }} {{ $employee->name }}  {{ $employee->patronymic }}</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="date">Дата</label>
                            <input type="date" value="{{ $event->date->format('Y-m-d') }}" class="form-control"
                                   id="date" name="date"
                                   placeholder="Дата" required>
                        </div>

                        <div class="form-group">
                            <label for="shift">Смена</label>
                            <select id="shift" class="form-control" name="shift" required>
                                <option value="" selected disabled hidden>Choose here</option>
                                <option value="1" {{ ($event->shift === 1) ? 'selected' : '' }}>Первая смена</option>
                                <option value="2" {{ ($event->shift === 2) ? 'selected' : '' }}>Вторая смена</option>
                                <option value="3" {{ ($event->shift === 3) ? 'selected' : '' }}>Третья смена</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-outline-primary">Обновить</button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script>
        $(document).ready(function () {
            $('.employee_input').show();
        });
    </script>
@stop

resources/views/event/index.blade.php
<div class="container p-2">
    <div class="row justify-content-center">
        @foreach($companiesWithEvents as $companyWithEvent)
            <table class="table">
                <thead>
                <tr class="table-info text-center">
                    <th colspan="7">{{ $companyWithEvent->name }}</th>
                </tr>
                <tr class="thead-light">
                    <th>Название проекта</th>
                    <th>Стоимость работ</th>
                    <th>Тип работ</th>
                    <th>Дата</th>
                    <th>Смена</th>
                    <th>Сотрудник</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($companyWithEvent->events as $event)
                    <tr>
                        <td>{{ $event->project_name }}</td>
                        <td>{{ $event->price }} $</td>
                        <td>{{ $event->type_work }}</td>
                        <td>{{ $event->date->day }} {{ $event->date->formatLocalized('%B') }}
                            , {{ $event->date->year }}</td>
                        <td>{{ $event->shift }}</td>
                        <td>{{ $event->employee->surname . ' ' . $event->employee->name . ' ' . $event->employee->patronymic }}</td>
                        <td>
                            <a href="{{ route('events.edit', $event) }}"
                               class="btn btn-block btn-primary btn-sm">edit</a>
                            <form method="post" action="{{ route('events.destroy', $event) }}"
                                  accept-charset="UTF-8" class="btn-block">
                                @csrf
                                <input type="hidden" name="_method" value="delete"/>
                                <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
                                <input class="btn btn-danger btn-block btn-sm" type="submit" value="delete"/>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        @endforeach
    </div>
</div>